version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: zapier_clone_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zapier_clone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: zapier_clone_migrate
    command: npx drizzle-kit migrate
    environment:
      DB_URL: postgresql://postgres:postgres@postgres:5432/zapier_clone
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/infrastructure/db/migrations:/usr/src/app/src/infrastructure/db/migrations



  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: zapier_clone_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"      # AMQP protocol
      - "15672:15672"    # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zapier_clone_api
    command: npm run start:api   # or node dist/api.js
    ports:
      - "3000:3000"
    environment:
      DB_URL: postgresql://postgres:postgres@postgres:5432/zapier_clone?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src   # optional for development

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zapier_clone_worker
    command: npm run start:worker   # or node dist/worker.js
    environment:
      DB_URL: postgresql://postgres:postgres@postgres:5432/zapier_clone
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src   # optional for development
    

volumes:
  postgres_data:
  rabbitmq_data:
