name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_DEV_CREDENTIALS }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker auth
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      ############################################
      # BUILD IMAGES
      ############################################

      - name: Build API image
        run: |
          docker build \
            --target runtime-api \
            -t us-central1-docker.pkg.dev/authentic-wharf-489916-k2/zapier-clone-ar-repo/api:latest \
            .

      - name: Push API image
        run: |
          docker push us-central1-docker.pkg.dev/authentic-wharf-489916-k2/zapier-clone-ar-repo/api:latest

      - name: Build Worker image
        run: |
          docker build \
            --target runtime-worker \
            -t us-central1-docker.pkg.dev/authentic-wharf-489916-k2/zapier-clone-ar-repo/worker:latest \
            .

      - name: Push Worker image
        run: |
          docker push us-central1-docker.pkg.dev/authentic-wharf-489916-k2/zapier-clone-ar-repo/worker:latest

      - name: Build Migrate image
        run: |
          docker build \
            --target migrate \
            -t us-central1-docker.pkg.dev/authentic-wharf-489916-k2/zapier-clone-ar-repo/migrate:latest \
            .

      - name: Push Migrate image
        run: |
          docker push us-central1-docker.pkg.dev/authentic-wharf-489916-k2/zapier-clone-ar-repo/migrate:latest

      ############################################
      # UPDATE MIGRATION JOB ENV
      ############################################

      - name: Update migrate job
        run: |
          gcloud run jobs update migrate \
            --image us-central1-docker.pkg.dev/authentic-wharf-489916-k2/zapier-clone-ar-repo/migrate:latest \
            --region us-central1 \
            --project authentic-wharf-489916-k2 \
            --set-env-vars DB_URL="${{ secrets.DB_URL }}"

      ############################################
      # RUN MIGRATIONS
      ############################################

      - name: Run migrations
        run: |
          gcloud run jobs execute migrate \
            --region us-central1 \
            --project authentic-wharf-489916-k2 \
            --wait

      ############################################
      # DEPLOY API
      ############################################

      - name: Deploy API
        run: |
          gcloud run deploy api \
            --image us-central1-docker.pkg.dev/authentic-wharf-489916-k2/zapier-clone-ar-repo/api:latest \
            --region us-central1 \
            --project authentic-wharf-489916-k2 \
            --allow-unauthenticated \
            --min-instances=1 \
            --max-instances=10 \
            --set-env-vars DB_URL="${{ secrets.DB_URL }}" \
            --service-account=api-sa@authentic-wharf-489916-k2.iam.gserviceaccount.com

      ############################################
      # DEPLOY WORKER
      ############################################

      - name: Deploy Worker
        run: |
          gcloud run deploy worker \
            --image us-central1-docker.pkg.dev/authentic-wharf-489916-k2/zapier-clone-ar-repo/worker:latest \
            --region us-central1 \
            --project authentic-wharf-489916-k2 \
            --no-allow-unauthenticated \
            --min-instances=1 \
            --max-instances=5 \
            --set-env-vars DB_URL="${{ secrets.DB_URL }}" \
            --service-account=worker-sa@authentic-wharf-489916-k2.iam.gserviceaccount.com
