name: ci

on:
  pull_request:
    branches: 
      - main
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Clean previous containers
        run: docker compose down -v || true

      - name: Start infrastructure
        run: docker compose up -d postgres rabbitmq migrate

      - name: Wait for migrations to finish
        run: docker compose logs -f migrate

      - name: Install dependencies
        run: npm ci --omit=optional

      - name: Run Tests
        run: npm run test
        env:
          TEST_DB_URL: postgresql://postgres:postgres@localhost:5433/zapier_clone
          RABBITMQ_URL: amqp://guest:guest@localhost:5672

      - name: Stop containers
        if: always()
        run: docker compose down -v


  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci --omit=optional

      - name: Run format checking
        run: npm run format:check

      - name: Check linting
        run: npm run lint -- --max-warnings=0